services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root12345
      POSTGRES_DB: postgres

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - postgres-db
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      POSTGRES_URL: postgres://root:root12345@postgres-db:5432/postgres
