FROM python:3.11

# workdir inside the container
WORKDIR /app

# copy requirements first (better for caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy the rest of the backend code
COPY . .

# run FastAPI with uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
